### PR TITLE
Update README.md: extend tested modems table

### PR DESCRIPTION
**Pull request by bam80**
Add eSIM type and QMI APDU backend

### CODE REVIEW

**Comment by bam80** [comment]
@stich86 did you have a chance to look into?

**Comment by stich86** [comment]
> @stich86 did you have a chance to look into?

I'm waiting other modules, so I'll add it to this PR and then merge it :)

**Comment by bam80** [comment]
Seems it's taking a long time.
Could we merge this already as it's about the info we have?

**Comment by stich86** [comment]
yes, i don't have an ETA for new modems to arrives..
so i'm merging it, then will add infos when i've done tests

**Comment by bam80** [comment]
@stich86 
Thanks, could you also check QMI APDU backend for Quectel RM502Q-GL and fill in the table?

**Pull request merged**
